-- CreateEnum
CREATE TYPE "Role" AS ENUM ('STAFF_OR_FACULTY', 'DIRECTOR', 'ADMIN_OR_PRINCIPAL', 'STUDENT_OR_PARENT', 'OTHER');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'STAFF_OR_FACULTY';
